// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyGame.Data;

#nullable disable

namespace MyGame.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyGame.Data.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "A fiery warrior from the volcanic lands, wielding dual blazing swords.",
                            Armor = 150,
                            Attack = 250,
                            Health = 1200,
                            Image = "img/blazefury.png",
                            Name = "Blazefury"
                        },
                        new
                        {
                            Id = 2,
                            About = "An icy mage from the frozen north, mastering frost magic to subdue enemies.",
                            Armor = 100,
                            Attack = 300,
                            Health = 800,
                            Image = "img/icy.png",
                            Name = "Frostbane"
                        },
                        new
                        {
                            Id = 3,
                            About = "A stealthy assassin who strikes from the shadows with precision and agility.",
                            Armor = 80,
                            Attack = 320,
                            Health = 900,
                            Image = "img/shadowblade.png",
                            Name = "Shadowblade"
                        },
                        new
                        {
                            Id = 4,
                            About = "A swift archer blessed by the wind gods, firing arrows with unerring accuracy.",
                            Armor = 120,
                            Attack = 240,
                            Health = 1000,
                            Image = "img/windrunner.png",
                            Name = "Windrunner"
                        },
                        new
                        {
                            Id = 5,
                            About = "A martial artist who channels the power of storms into electrifying punches.",
                            Armor = 100,
                            Attack = 260,
                            Health = 1100,
                            Image = "img/thunderfist.png",
                            Name = "Thunderfist"
                        },
                        new
                        {
                            Id = 6,
                            About = "A massive titan who wields the strength of the earth to crush his foes.",
                            Armor = 200,
                            Attack = 200,
                            Health = 1400,
                            Image = "img/earthshaker.png",
                            Name = "Earthshaker"
                        },
                        new
                        {
                            Id = 7,
                            About = "A radiant healer who channels divine energy to heal allies and smite foes.",
                            Armor = 80,
                            Attack = 220,
                            Health = 900,
                            Image = "img/celestia.png",
                            Name = "Celestia"
                        },
                        new
                        {
                            Id = 8,
                            About = "A toxic hunter who uses poison-tipped weapons to weaken and destroy enemies.",
                            Armor = 90,
                            Attack = 230,
                            Health = 950,
                            Image = "img/venomstrike.png",
                            Name = "Venomstrike"
                        });
                });

            modelBuilder.Entity("MyGame.Data.Models.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Creatures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 45,
                            Defense = 30,
                            Health = 180,
                            Name = "Dark Warlock"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 38,
                            Defense = 35,
                            Health = 210,
                            Name = "Frost Revenant"
                        },
                        new
                        {
                            Id = 3,
                            Attack = 60,
                            Defense = 25,
                            Health = 320,
                            Name = "Infernal Behemoth"
                        },
                        new
                        {
                            Id = 4,
                            Attack = 42,
                            Defense = 20,
                            Health = 150,
                            Name = "Venomous Widow"
                        },
                        new
                        {
                            Id = 5,
                            Attack = 50,
                            Defense = 15,
                            Health = 140,
                            Name = "Shadow Assassin"
                        },
                        new
                        {
                            Id = 6,
                            Attack = 35,
                            Defense = 10,
                            Health = 100,
                            Name = "Cursed Wraith"
                        },
                        new
                        {
                            Id = 7,
                            Attack = 48,
                            Defense = 40,
                            Health = 250,
                            Name = "Crimson Ogre"
                        },
                        new
                        {
                            Id = 8,
                            Attack = 33,
                            Defense = 25,
                            Health = 170,
                            Name = "Bone Collector"
                        },
                        new
                        {
                            Id = 9,
                            Attack = 20,
                            Defense = 50,
                            Health = 300,
                            Name = "Iron Golem"
                        },
                        new
                        {
                            Id = 10,
                            Attack = 40,
                            Defense = 30,
                            Health = 200,
                            Name = "Plague Harbinger"
                        },
                        new
                        {
                            Id = 11,
                            Attack = 55,
                            Defense = 20,
                            Health = 220,
                            Name = "Savage Werewolf"
                        },
                        new
                        {
                            Id = 12,
                            Attack = 45,
                            Defense = 35,
                            Health = 210,
                            Name = "Void Stalker"
                        },
                        new
                        {
                            Id = 13,
                            Attack = 25,
                            Defense = 50,
                            Health = 250,
                            Name = "Arcane Sentinel"
                        },
                        new
                        {
                            Id = 14,
                            Attack = 42,
                            Defense = 22,
                            Health = 170,
                            Name = "Blazing Salamander"
                        },
                        new
                        {
                            Id = 15,
                            Attack = 50,
                            Defense = 15,
                            Health = 180,
                            Name = "Soul Reaver"
                        },
                        new
                        {
                            Id = 16,
                            Attack = 48,
                            Defense = 18,
                            Health = 190,
                            Name = "Nightmare Fiend"
                        },
                        new
                        {
                            Id = 17,
                            Attack = 55,
                            Defense = 30,
                            Health = 280,
                            Name = "Titan Basilisk"
                        },
                        new
                        {
                            Id = 18,
                            Attack = 70,
                            Defense = 40,
                            Health = 350,
                            Name = "Chaos Dragon"
                        },
                        new
                        {
                            Id = 19,
                            Attack = 30,
                            Defense = 20,
                            Health = 120,
                            Name = "Ethereal Specter"
                        },
                        new
                        {
                            Id = 20,
                            Attack = 60,
                            Defense = 25,
                            Health = 240,
                            Name = "Vampiric Duke"
                        },
                        new
                        {
                            Id = 21,
                            Attack = 35,
                            Defense = 25,
                            Health = 190,
                            Name = "Gravebound Lich"
                        },
                        new
                        {
                            Id = 22,
                            Attack = 40,
                            Defense = 15,
                            Health = 160,
                            Name = "Ashen Harpy"
                        },
                        new
                        {
                            Id = 23,
                            Attack = 50,
                            Defense = 40,
                            Health = 290,
                            Name = "Rotting Colossus"
                        },
                        new
                        {
                            Id = 24,
                            Attack = 47,
                            Defense = 28,
                            Health = 220,
                            Name = "Thunder Warden"
                        },
                        new
                        {
                            Id = 25,
                            Attack = 58,
                            Defense = 32,
                            Health = 310,
                            Name = "Hellbound Minotaur"
                        },
                        new
                        {
                            Id = 26,
                            Attack = 53,
                            Defense = 27,
                            Health = 260,
                            Name = "Twilight Chimera"
                        },
                        new
                        {
                            Id = 27,
                            Attack = 62,
                            Defense = 30,
                            Health = 300,
                            Name = "Serpent Empress"
                        },
                        new
                        {
                            Id = 28,
                            Attack = 45,
                            Defense = 35,
                            Health = 200,
                            Name = "Phantom Knight"
                        },
                        new
                        {
                            Id = 29,
                            Attack = 50,
                            Defense = 15,
                            Health = 190,
                            Name = "Bloodthirster Fiend"
                        },
                        new
                        {
                            Id = 30,
                            Attack = 40,
                            Defense = 25,
                            Health = 200,
                            Name = "Nether Beast"
                        },
                        new
                        {
                            Id = 31,
                            Attack = 30,
                            Defense = 55,
                            Health = 330,
                            Name = "Frozen Colossus"
                        },
                        new
                        {
                            Id = 32,
                            Attack = 48,
                            Defense = 25,
                            Health = 210,
                            Name = "Savage Centaur"
                        },
                        new
                        {
                            Id = 33,
                            Attack = 45,
                            Defense = 20,
                            Health = 180,
                            Name = "Dread Scorpion"
                        },
                        new
                        {
                            Id = 34,
                            Attack = 38,
                            Defense = 40,
                            Health = 240,
                            Name = "Blighted Treant"
                        },
                        new
                        {
                            Id = 35,
                            Attack = 60,
                            Defense = 28,
                            Health = 320,
                            Name = "Infernal Colossus"
                        },
                        new
                        {
                            Id = 36,
                            Attack = 42,
                            Defense = 35,
                            Health = 230,
                            Name = "Storm Djinn"
                        },
                        new
                        {
                            Id = 37,
                            Attack = 47,
                            Defense = 22,
                            Health = 210,
                            Name = "Desert Manticore"
                        },
                        new
                        {
                            Id = 38,
                            Attack = 55,
                            Defense = 20,
                            Health = 250,
                            Name = "Bone Wyvern"
                        },
                        new
                        {
                            Id = 39,
                            Attack = 50,
                            Defense = 18,
                            Health = 190,
                            Name = "Venomfang Naga"
                        },
                        new
                        {
                            Id = 40,
                            Attack = 52,
                            Defense = 25,
                            Health = 230,
                            Name = "Ravenous Gorgon"
                        },
                        new
                        {
                            Id = 41,
                            Attack = 40,
                            Defense = 30,
                            Health = 180,
                            Name = "Void Leaper"
                        },
                        new
                        {
                            Id = 42,
                            Attack = 65,
                            Defense = 20,
                            Health = 230,
                            Name = "Chaos Warlock"
                        },
                        new
                        {
                            Id = 43,
                            Attack = 33,
                            Defense = 45,
                            Health = 290,
                            Name = "Glacial Yeti"
                        },
                        new
                        {
                            Id = 44,
                            Attack = 48,
                            Defense = 30,
                            Health = 240,
                            Name = "Crystal Wyrm"
                        },
                        new
                        {
                            Id = 45,
                            Attack = 35,
                            Defense = 18,
                            Health = 150,
                            Name = "Skeletal Sorcerer"
                        },
                        new
                        {
                            Id = 46,
                            Attack = 68,
                            Defense = 25,
                            Health = 340,
                            Name = "Hellfire Demon"
                        },
                        new
                        {
                            Id = 47,
                            Attack = 30,
                            Defense = 12,
                            Health = 120,
                            Name = "Forest Banshee"
                        },
                        new
                        {
                            Id = 48,
                            Attack = 62,
                            Defense = 40,
                            Health = 360,
                            Name = "Titan Leviathan"
                        },
                        new
                        {
                            Id = 49,
                            Attack = 52,
                            Defense = 25,
                            Health = 220,
                            Name = "Silverback Gorilla"
                        },
                        new
                        {
                            Id = 50,
                            Attack = 70,
                            Defense = 35,
                            Health = 350,
                            Name = "Lava Behemoth"
                        },
                        new
                        {
                            Id = 51,
                            Attack = 40,
                            Defense = 20,
                            Health = 160,
                            Name = "Soulshade Phantom"
                        },
                        new
                        {
                            Id = 52,
                            Attack = 38,
                            Defense = 20,
                            Health = 140,
                            Name = "Feral Spirit"
                        },
                        new
                        {
                            Id = 53,
                            Attack = 68,
                            Defense = 32,
                            Health = 320,
                            Name = "Corrupted Phoenix"
                        });
                });

            modelBuilder.Entity("MyGame.Data.Models.SpecialSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("SpecialSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 300,
                            CharacterId = 1,
                            Health = 0,
                            Name = "Flame Slash"
                        },
                        new
                        {
                            Id = 2,
                            Attack = 0,
                            CharacterId = 1,
                            Health = 150,
                            Name = "Molten Shield"
                        },
                        new
                        {
                            Id = 3,
                            Attack = 400,
                            CharacterId = 1,
                            Health = -50,
                            Name = "Inferno Burst"
                        },
                        new
                        {
                            Id = 4,
                            Attack = 320,
                            CharacterId = 2,
                            Health = 0,
                            Name = "Frost Nova"
                        },
                        new
                        {
                            Id = 5,
                            Attack = 0,
                            CharacterId = 2,
                            Health = 200,
                            Name = "Ice Barrier"
                        },
                        new
                        {
                            Id = 6,
                            Attack = 350,
                            CharacterId = 2,
                            Health = -30,
                            Name = "Blizzard Storm"
                        },
                        new
                        {
                            Id = 7,
                            Attack = 400,
                            CharacterId = 3,
                            Health = 0,
                            Name = "Shadow Strike"
                        },
                        new
                        {
                            Id = 8,
                            Attack = 0,
                            CharacterId = 3,
                            Health = 100,
                            Name = "Smoke Bomb"
                        },
                        new
                        {
                            Id = 9,
                            Attack = 250,
                            CharacterId = 3,
                            Health = -20,
                            Name = "Phantom Dash"
                        },
                        new
                        {
                            Id = 10,
                            Attack = 280,
                            CharacterId = 4,
                            Health = 0,
                            Name = "Piercing Shot"
                        },
                        new
                        {
                            Id = 11,
                            Attack = 200,
                            CharacterId = 4,
                            Health = 50,
                            Name = "Wind Gust"
                        },
                        new
                        {
                            Id = 12,
                            Attack = 350,
                            CharacterId = 4,
                            Health = -40,
                            Name = "Hurricane Volley"
                        },
                        new
                        {
                            Id = 13,
                            Attack = 350,
                            CharacterId = 5,
                            Health = 0,
                            Name = "Lightning Strike"
                        },
                        new
                        {
                            Id = 14,
                            Attack = 300,
                            CharacterId = 5,
                            Health = 0,
                            Name = "Storm Punch"
                        },
                        new
                        {
                            Id = 15,
                            Attack = 250,
                            CharacterId = 5,
                            Health = 80,
                            Name = "Thunderclap"
                        },
                        new
                        {
                            Id = 16,
                            Attack = 250,
                            CharacterId = 6,
                            Health = 100,
                            Name = "Seismic Slam"
                        },
                        new
                        {
                            Id = 17,
                            Attack = 300,
                            CharacterId = 6,
                            Health = 50,
                            Name = "Earthquake"
                        },
                        new
                        {
                            Id = 18,
                            Attack = 0,
                            CharacterId = 6,
                            Health = 400,
                            Name = "Stone Wall"
                        },
                        new
                        {
                            Id = 19,
                            Attack = 0,
                            CharacterId = 7,
                            Health = 300,
                            Name = "Healing Light"
                        },
                        new
                        {
                            Id = 20,
                            Attack = 0,
                            CharacterId = 7,
                            Health = 400,
                            Name = "Divine Shield"
                        },
                        new
                        {
                            Id = 21,
                            Attack = 350,
                            CharacterId = 7,
                            Health = -50,
                            Name = "Holy Wrath"
                        },
                        new
                        {
                            Id = 22,
                            Attack = 300,
                            CharacterId = 8,
                            Health = 0,
                            Name = "Poison Dart"
                        },
                        new
                        {
                            Id = 23,
                            Attack = 250,
                            CharacterId = 8,
                            Health = -20,
                            Name = "Toxic Cloud"
                        },
                        new
                        {
                            Id = 24,
                            Attack = 350,
                            CharacterId = 8,
                            Health = 50,
                            Name = "Venomous Bite"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyGame.Data.Models.SpecialSkill", b =>
                {
                    b.HasOne("MyGame.Data.Models.Character", "Character")
                        .WithMany("SpecialSkills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MyGame.Data.Models.Character", b =>
                {
                    b.Navigation("SpecialSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
